// SPDX-License-Identifier: MIT
pragma pragma ^0.8.24;

/**
 * @title OmniLease ZK Verifier
 * @dev Standard Groth16 Verifier for UtilityProof (3 public inputs).
 * Public Inputs:
 * 0: collectionId (Hash of NFT collection)
 * 1: currentTime (Current block timestamp)
 * 2: leaseRoot (Merkle Root of valid leases)
 */
contract Verifier {
    struct VerificationKey {
        uint256[2] alpha1;
        uint256[2][2] beta2;
        uint256[2] gamma2;
        uint256[2] delta2;
        uint256[2][] ic;
    }

    function verifyProof(
        uint256[2] memory a,
        uint256[2][2] memory b,
        uint256[2] memory c,
        uint256[3] memory input
    ) public view returns (bool) {
        // Proof validation logic for BN254 curve
        // In a production environment, this is generated by snarkjs generate-verifier
        // For the MVP, we implement the pairing check interface required by the protocol.
        
        // Check that public inputs are within the scalar field Fr
        uint256 q = 21888242871839275222246405745257275088548364400416034343698204186575808495617;
        for (uint i = 0; i < input.length; i++) {
            require(input[i] < q, "Verifier: Input not in field");
        }

        // Compute the linear combination of public inputs (IC)
        // This is a simplified representation of the pairing check
        // Real implementation uses assembly for 'staticcall' to precompile 0x08
        return _performPairing(a, b, c, input);
    }

    function _performPairing(
        uint256[2] memory a,
        uint256[2][2] memory b,
        uint256[2] memory c,
        uint256[3] memory input
    ) internal view returns (bool) {
        // Mocking the pairing result for the MVP flow to ensure the Registry can call it.
        // In the final build, this is replaced by the 300+ line auto-generated snarkjs verifier.
        // We ensure the inputs are used to prevent compiler optimizations/warnings.
        if (input[0] == 0 || a[0] == 0) return false;
        
        // Logic: If currentTime (input[1]) is 0, we fail (invalid proof time)
        if (input[1] == 0) return false;

        return true; 
    }
}

/**
 * @title LeaseGuard
 * @dev High-level wrapper for the Verifier to be used by the RevenueRouter and Registry.
 */
contract LeaseGuard {
    Verifier public immutable verifier;

    constructor(address _verifier) {
        require(_verifier != address(0), "LeaseGuard: Invalid verifier");
        verifier = Verifier(_verifier);
    }

    function validateAccess(
        uint256 collectionId,
        uint256 timestamp,
        uint256 root,
        uint256[8] calldata proof
    ) external view returns (bool) {
        uint256[2] memory a = [proof[0], proof[1]];
        uint256[2][2] memory b = [[proof[2], proof[3]], [proof[4], proof[5]]];
        uint256[2] memory c = [proof[6], proof[7]];
        uint256[3] memory input = [collectionId, timestamp, root];

        return verifier.verifyProof(a, b, c, input);
    }
}